# Generated by Django 4.0 on 2025-08-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'verbose_name': 'Фото галереї', 'verbose_name_plural': 'Фото галереї'},
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='gallery/', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата зміни'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва'),
        ),
    ]
